name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: pre-commit/action@v3.0.1

      - name: Install system dependencies for PDF docs
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            make \
            latexmk \
            pandoc \
            graphviz \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-science \
            texlive-pictures \
            texlive-xetex \
            texlive-luatex \
            texlive-plain-generic

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel

          pip install '.[dev]'

          pip install \
            pytest \
            pytest-cov \
            sphinx \
            myst-parser \
            sphinx-autodoc-typehints \
            sphinx-rtd-theme \
            sphinx-copybutton \
            sphinx-design \
            sphinxcontrib-bibtex \
            sphinxcontrib-mermaid \
            nbsphinx \
            numpydoc \
            furo \
            pydata-sphinx-theme \
            ipython \
            ipykernel \
            jupyter \
            matplotlib \
            graphviz

      - name: Build docs PDF
        working-directory: docs
        run: make latexpdf

      - name: Upload docs PDF
        uses: actions/upload-artifact@v4
        with:
          name: kinisi-docs-pdf-python-${{ matrix.python-version }}
          path: docs/_build/latex/*.pdf
          if-no-files-found: error

      - name: Run check
        run: make check

      - name: Run distcheck
        run: make distcheck
